### PR TITLE
Prepare for packagist publishing

### PR DESCRIPTION
**Pull request by mallardduck**
This PR is still a WIP however will accomplish the following:

1. - [x] Clean-up code styles to fit PSR12,
2. - [x] Add GH actions and integrations for testing,
3. - [x] Add/edit repo meta-data and maintence files (gitignore, gitattributes, etc)
4. - [ ] Rename the project to a more fitting name
5. - [x] Add PHPunit based tests for complete (or near) coverage

### CODE REVIEW

**Comment by mallardduck** [comment]
So @RobThree, first I want to say I'm sorry how massive the changes look to the main file. This seems to be it using Windows style line endings however PSR12 prefers unix style line endings. Aside from that fact obscuring what I touched, I've done what I can to ensure that all backwards compatibility should be kept with these changes.

That said, the changes here also setup future releases to deprecate certain things. Then at a time when PHP 7.4 support is removed even more could be removed and some logic refactored for PHP 8s Enums.

All that remains is choosing a more apt name for the package and applying those changes to the PR. As mentioned in the issue #1 here are a few ideas I'm inclined to:

- Scrabble IDs, as a homage to the game and the IDs being word based
- Fun-Friendly-Human IDs, a very not subtle name based on a potential ID
- WordSet IDs, a more literal choice since the IDs are generated by user provided "word sets"

**Comment by RobThree** [comment]
First of all: Thank you very much for all the work you've put it! It's a LOT! I've looked over each and every commit and can't say I noticed any issues so far. There are a few considerations I'd like to discuss:

* Getting rid of `toUrl` and `parseUrl`; they're just aliases for `parseId` and `generate`.
* I think I'd like to provide an interface (`IFutureProjectNameGenrator`) for the `UrlGenerator` (whereas the `UrlGenerator` name is also something we should consider changing to something more generic)

Other than that: Great work! 👊

**Comment by mallardduck** [comment]
> Getting rid of toUrl and parseUrl; they're just aliases for parseId and generate.
 Rock on, I like that too. I've been writing things with a "backward compatible" idea in mind. But I guess if it hadn't been published to packagist yet the odds are minimal that this is a concern. 😅  I should have realized that but old habits die hard. 

> I think I'd like to provide an interface (IFutureProjectNameGenrator) for the UrlGenerator (whereas the UrlGenerator name is also something we should consider changing to something more generic)

Ohh, I think I can pick up what you're putting down here. This could lead to very interesting possibilities.

**Comment by RobThree** [comment]
I don't think the interface will have to be very exciting, I'd like to keep it as clean as possible:

```php
public interface IWhatever {
    public function generate(int $id): string;
    public function parseId(string $text): int;
}
```

Something like this. It could even be split up into an `IWhateverGenerator` and an `IWhateverParser` but I think that's overkill.

Looking at it I do think that in line with `parse*Id*` I think it's also a good idea to rename `generate` to `generate*Id*`. However, maybe leave that for later. Should we decide to call it a FooGenerator we could name the methods `parseFoo()` and `generateFoo()`. And now I think of it, maybe it would be even beter to just name the methods `generate()` (or `create()`) and `parse()` and leave out the `Id` (or `Foo`) part alltogether; they're methods on a **Id**Generator / **Foo**Generator class afterall.

**Comment by RobThree** [comment]
So I guess the only "big" issue left is coming up with a decent name?

**Comment by mallardduck** [comment]
And what a task choosing the "right" name is! While I like some of the ideas I suggested above, I don't really love one more than the rest. They are all pretty much equally average for me.

So I've started to do some casual chatting on the PHP community via twitter. Getting some decent engagement and chats around it - still nothing jumping out at me though.

If you want to follow along:

Main thread: https://twitter.com/dan_in_tweets/status/1516755357342777348
PHP Community thread: https://twitter.com/dan_in_tweets/status/1516755675120033796

**Comment by RobThree** [comment]
> And what a task choosing the "right" name is!

As usual 🤣

> If you want to follow along:
> 
> Main thread: https://twitter.com/dan_in_tweets/status/1516755357342777348
> PHP Community thread: https://twitter.com/dan_in_tweets/status/1516755675120033796

The PHP Community thread shows "This Tweet is unavailable."?

I'll retweet and ask my followers as well. And I'll have a sitdown tonight to clear my mind and try to come up with something.

**Comment by RobThree** [comment]
🤔... Come to think of it. Maybe we're asking the wrong question. I think the real question is: what do you call this specific `int` <-> `string` conversion. Maybe there's a ~wordle~ word for it? 😉

**Comment by RobThree** [comment]
> Direct community link here: https://twitter.com/i/communities/1493441201487298561

Shows:

> Hmm...this page doesn’t exist. Try searching for something else.

But it's ok, I'll hear from you whenever something interesting comes up there 😉

**Comment by mallardduck** [comment]
Absolutely, will keep you updated. I've started a google sheet and captured all the suggestions so far.

https://docs.google.com/spreadsheets/d/10hy5m9tgmurydX1j0QJUb2iCpIRVFJL0m3eDX3XDkbY/edit?usp=sharing

**Comment by MueR** [comment]
I really like `humanoid` to be honest.

**Comment by RobThree** [comment]
> I really like `humanoid` to be honest.

So do I. As well as Guid-o 😂

Really good and cool suggestions so far! Let's give it a few hours. Great work @mallardduck !

**Comment by MueR** [comment]
I really only have one nit-picky thingie to nitpick. There's one generic Exception class, which extends the bare `\Exception` class, While I understand the choice, since it's used as both a `\RuntimeException` and an `\InvalidArgumentException`, perhaps it would be better to split the exceptions into more error-specific exceptions?

**Review by MueR — APPROVED** [review]
Looks great to me :)

**Comment by RobThree** [comment]
@MueR : Would you like to be added as an author (maintainer) too? (see 251474f)

**Comment by RobThree** [comment]
Barely anything != nothing.

If @mallardduck is ok with it then I'll merge this PR tonight as-is. Unless something better comes up I'd like to go with HumanoID as project name (main classname?) and make the appropriate changes for it. Then I'll go over the README and update it where needed and update the composer file to add @MueR.

Does this sparkle for everyone?

**Comment by mallardduck** [comment]
Yeah that jives well with me - I like HumanoID a lot.
Sounds great to me!

**Comment by RobThree** [comment]
A little less serious: I was looking for a package icon; how about a (slightly modified version of) [this one](https://www.flaticon.com/free-icon/chatbot_7323564?related_id=7323564&origin=search)?

chatbot 
[Larger version](https://user-images.githubusercontent.com/607888/164258793-4c3dbf9b-fbcf-4131-8468-a2cb72d2ca82.png)

I like the idea of a Robot (being the 'opposite' of a human). And a little speechbubble (or two) to imply the int <-> string conversion. I usually get my icons (with proper attributiono ofcourse) from flaticon.com. You can see more examples [here](https://www.flaticon.com/search?word=robot). If anyone can find a better one: I'm open to suggestions until 20:00 CEST 😜

**Comment by MueR** [comment]
> A little less serious: I was looking for a package icon; how about a (slightly modified version of) [this one](https://www.flaticon.com/free-icon/chatbot_7323564?related_id=7323564&origin=search)?
> 
> chatbot [Larger version](https://user-images.githubusercontent.com/607888/164258793-4c3dbf9b-fbcf-4131-8468-a2cb72d2ca82.png)
> 
> I like the idea of a Robot (being the 'opposite' of a human). And a little speechbubble (or two) to imply the int <-> string conversion. I usually get my icons (with proper attributiono ofcourse) from flaticon.com. You can see more examples [here](https://www.flaticon.com/search?word=robot). If anyone can find a better one: I'm open to suggestions until 20:00 CEST 😜
humanoid
How about this?

**Comment by RobThree** [comment]
image

Work in progress...

**Pull request merged**
